# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Pull Request TestCI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing node modules
        run: npm install

      - name: Testing the node modules
        run: npm test

  validate-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compressing the project to the zip file
        run: zip -r webapp.zip .

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run packer init
        id: init
        run: "packer init ."

      - name: Run packer validate
        id: validate
        run: "packer validate -var-file=main.pkrvars.hcl ."
